name: POSEFREE Final APK Generator

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x posecam---android-photography-app/gradlew

    - name: Build Debug APK
      run: |
        cd posecam---android-photography-app
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: PoseFree-Photography-APK
        path: posecam---android-photography-app/app/build/outputs/apk/debug/app-debug.apk
